image: docker:latest

services:
- docker:dind

stages:
- build_publish

before_script:
- apk add bash

cron_or_supervisord:
  stage: build_publish
  script:
  - /bin/bash utils/publish/feature--cron-or-supervisord.sh
  only:
  - feature--cron-or-supervisord

staging:
  stage: build_publish
  script:
  - /bin/bash utils/publish/staging.sh
  only:
  - staging

production:
  stage: build_publish
  script:
  - /bin/bash utils/publish/production.sh
  only:
  - tags
  except:
  - branches

update_docker_hub_full_description:
  stage: build_publish
  script:
    - /bin/bash utils/publish/update-docker-hub-full-description.sh
  only:
    - master