image: docker:latest

services:
- docker:dind

stages:
- build_publish

before-script:
  - apk add bash

staging:
  stage: build_publish
  script:
  - /bin/bash utils/publish/staging.sh
  only:
  - staging

production:
  stage: build_publish
  script:
  - /bin/bash utils/publish/production.sh
  only:
  - tags
  except:
  - branches
