image: docker:latest

services:
- docker:dind

stages:
- build_publish

staging:
  stage: build_publish
  before_script:
  - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
  - /bin/bash utils/publish/staging
  only:
  - staging

production:
  stage: build_publish
  before_script:
  - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
  - /bin/bash utils/publish/production.sh
  only:
  - tags
  except:
  - branches